title: Swoop 
email: dan@cohelix.co.nz
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.cohelix.co.nz" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
